### ISSUE TITLE
getUri is not a function

### ISSUE THREAD

**Issue by kennethchoe** [jamesmbourne/aws4-axios#1139]
I tried various versions and couldn't figure out what I am doing wrong here. When I run `axios.get('url')`, I get `u.getUri is not a function` error.

```
import axiosOriginal from "axios";
import { Alert } from "./pageSlice";
import { aws4Interceptor } from "aws4-axios";
import { getCredentialsFunc } from "my-custom-package";

const axios = axiosOriginal.create();

const interceptor = aws4Interceptor({
    options: {
        region: "us-west-2",
        service: "execute-api",
    },
    credentials: {
        getCredentials: getCredentialsFunc
    },
});

axios.interceptors.request.use(interceptor);
```

I confirmed that `await getCredentialsFunc();` gives something that looks like credentials. The error is coming from [this line](https://github.com/jamesmbourne/aws4-axios/blob/3a5e7044d91f450a86a55220e3ae61f7c2550b93/src/interceptor.ts#L115) of `aws4-axios` source code.

```
  return async (config) => {
    const url = instance.getUri(config);
```
When I debug, instance is not an object but a plain string that points to some static link, such as `/static/media/axios.e7d77f0967a69d31d7fc.cjs`, which does not have getUri() function, hence the error message (u is minified from instance). 

Any help would be much appreciated.

**Comment by jamesmbourne** [comment]
@kennethchoe could you let me know what versions of axios and aws4-axios you have installed?

**Comment by kennethchoe** [comment]
package.json:
```
        "aws4-axios": "^3.2.24",
        "axios": "^1.4.0",
```
Just confirmed they are 3.2.24 and 1.4.0 under `node_modules`.

I was able to make it work with aws-sdk package 2.1424.0 without using aws4-axios in a less nice way :), so I can also confirm that `getCredentialsFunc` is good.

**Comment by jamesmbourne** [comment]
@kennethchoe can you try passing your Axios instance (`axios`) into the interceptor via the `instance` option?

https://github.com/jamesmbourne/aws4-axios/blob/main/src/interceptor.ts#L98

**Comment by kennethchoe** [comment]
I actually tried that since I found that usage from [interceptor.test.ts](https://github.com/jamesmbourne/aws4-axios/blob/main/src/interceptor.test.ts#L56). I just retried and am getting a different error: `o.parse is not a function`

I think it is coming from [aws4 code](https://github.com/mhart/aws4/blob/317c243e311f06b0722ffb3124508e6f55388fe8/aws4.js#L355), guessing based on my transpiled code.

**Comment by jamesmbourne** [comment]
@kennethchoe I was not able to reproduce this in a Node.js project - could you push a minimal example project up to GitHub? I suspect this may be something to do with how the code is being bundled.

Are you using this in a frontend application? I'm not sure how supported that is by `aws4`, the README includes the following:
> If you want to sign and send AWS requests in a browser, or an environment like [Cloudflare Workers](https://developers.cloudflare.com/workers/), then check out [aws4fetch](https://github.com/mhart/aws4fetch) – otherwise you can also bundle this library for use [in older browsers](https://github.com/mhart/aws4/blob/master/browser).

**Comment by kennethchoe** [comment]
I missed that - sorry and thank you for your time and the clarification. My project is frontend application.
